#!/bin/bash

source venv/bin/activate

FILENAME="$(basename "$1")"
FILE="${FILENAME%.*}"
python3 ./quack_front.py -r "$1" > ./tmp.txt
cd ./tiny_vm/
COUNT=$(ls ../tmp | wc -l)
for ((i=0;i<COUNT;i++)); do # I hate this accounts for order of imports
    for file in $(ls ../tmp); do
	echo "Creating $file"
	$(touch "./OBJ/${file%.*}.json")
	python3 assemble.py "../tmp/$file" "./OBJ/${file%.*}.json"
    done
done
for file in $(ls ../tmp); do
    echo "Removing $file"
    # Remove the temporary file
    rm "../tmp/$file"
    # Delete the file after processing
done
./bin/tiny_vm "$FILE"
